feat: :sparkles: Initial commit
ntokozo-nhlangulela/manga-app pull request #1
Opened 2023-03-14 23:34 UTC by ntokozo-nhlangulela

Added cards to the code.

2023-03-16 17:58 UTC, CharelMarais reviewed
Please check the comments and make adjustments if not being worked on in a separate branch.

2023-03-16 17:58 UTC, CharelMarais commented on src/components/mangaCard.tsx
> +const T = () => {
The name T does not explain what the component does.

2023-03-16 17:58 UTC, CharelMarais commented on src/components/mangaCard.tsx
> +    // MangaApis.getMangaDetails(mangaId).then((response) => {
Make sure to remove any commented code

2023-03-20 14:05 UTC, sechaba-mache requested changes
Remove commented code and rename component T as mentioned by Charel

2023-03-22 07:00 UTC, merged